// Generated by Wrangler by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
// biome-ignore lint/suspicious/noEmptyInterface: <explanation>
interface Env {}
